[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
antsol_registry = "A9igkBugcujD9Nw9d97FFN4aY3qHXnJxEqCChJt8C42S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/antsol-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
